services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-db
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: mydatabase
    ports:
      - "3000:3000"
    networks:
      - backend-db
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8000:3000"
    depends_on:
      - backend
volumes:
  postgres_data:

networks:
  backend-db: