version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dart-scorer-network
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: mydatabase
    ports:
      - "3000:3000" # Expose the backend port
    networks:
      - dart-scorer-network
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80" # Expose the frontend port
    networks:
      - dart-scorer-network
volumes:
  postgres_data:

networks:
  dart-scorer-network:
    driver: bridge