apiVersion: apps/v1
kind: Deployment
metadata:
  name: dart-scorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dart-scorer
  template:
    metadata:
      labels:
        app: dart-scorer
    spec:
      containers:
        - name: dart-scorer
          image: comhendrik/dart-scorer-frontend-only:1.0.0  # Replace with your Docker Hub image
          ports:
            - containerPort: 80